### ISSUE TITLE
Can't open Jekyll::Strapi classes

### ISSUE THREAD

**Issue by mkrajewski90** [bluszcz/jekyll-strapi-4#23]
Hey,

After update the gem from jekyll-strapi to jekyll-strapi-4 I see the problem with reopen any class.

```
module Jekyll
  module Strapi
    class StrapiCollection
      def custom_path_params
        "&locale=#{@site.config["lang"]}"
      end
    end
  end
end
```

`NameError: uninitialized constant Jekyll::Strapi`

This error doesn't occur before when connect to your develop branch.

Do you know what's wrong here?

**Comment by mkrajewski90** [comment]
Temporary solution I see here is to require jekyll file
`require "jekyll-strapi"`

It works but before there was no need to require anything.

**Comment by bluszcz** [comment]
@mkrajewski90 what do you have in plugins?

For this plugin we should set:
```
plugins:
  - jekyll-strapi-4
```
which perhaps was not properly implemented during the _rebranding_ to -4. Checking it now.
